name: terraform

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    concurrency:
      cancel-in-progress: false
      group: tf-lock
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4

      - run: terraform fmt -check
        working-directory: ./terraform

      - run: terraform init
        working-directory: ./terraform

      - run: terraform validate
        working-directory: ./terraform

  plan:
    concurrency:
      cancel-in-progress: false
      group: tf-lock
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs:
      - check

    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4

      - run: terraform init
        working-directory: ./terraform

      - run: terraform plan -out "terraform.tfplan"
        working-directory: ./terraform

      - uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: terraform/terraform.tfplan

  apply:
    concurrency:
      cancel-in-progress: false
      group: tf-lock
    environment:
      name: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    if: github.ref == 'refs/heads/main'
    needs:
      - plan

    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tf-plan

      - run: mv terraform.tfplan ./terraform/terrafform.tfplan

      - run: terraform init
        working-directory: ./terraform

      - run: terraform apply "terraform.tfplan"
        working-directory: ./terraform
